<?php

namespace App\Repositories;

use App\Models\Notice;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class NoticeRepositories extends BaseRepository
{
    /**
     * NoticeRepositories constructor.
     */
    public function __construct()
    {
    }

    public function create($input)
    {
        return Notice::create($input); // TODO: Change the autogenerated stub
    }


    public function getNotices($keyword, $limit)
    {
        $query = DB::table('notices');
        if ($keyword) {
            $query = $query->where('title', 'like', '%' . $keyword . '%');
        }

        return $query->orderBy('id', 'desc')->paginate($limit);
    }

    public function createNotice($params)
    {
        $notice = new Notice();
        $notice->title = $params->title;
        $notice->content = $params->content;
        $notice->author = Auth::guard('admin')->user()->name;
        $notice->save();
        return;
    }

    public function getNotice($id)
    {
        $data = DB::table('notices')->find($id);
        return $data;
    }
}
