apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: exchange-cicd-dev
  region: ap-northeast-2

vpc:
  id: vpc-0bd37d37ac2f47d7f
  subnets:
    public:
      ap-northeast-2a:
        id: subnet-076c4ac4f0d50e9d1
      ap-northeast-2b:
        id: subnet-067f8cfa6ed2a8798
      ap-northeast-2c:
        id: subnet-0e0293fc65c7a25f5

managedNodeGroups:
  - name: ng-spot-1
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    spot: true
    volumeSize: 50
    labels:
      role: worker
    tags:
      Environment: dev
      Project: exchange-cicd

iam:
  withOIDC: true
