FROM ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ENV-dr-ex-base:php-8.1-cli
WORKDIR /var/www/gs-api

RUN apt-get update -y &&\
    apt-get install -y libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev libfreetype6-dev libzip-dev zip vim curl cron libmagickwand-dev imagemagick &&\
    apt-get install -y --no-install-recommends \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev &&\
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install gd pdo pdo_mysql bcmath pcntl sysvmsg sockets zip opcache
# RUN touch /usr/local/etc/php/conf.d/uploads.ini \
#     && echo "upload_max_filesize = 80M;" >> /usr/local/etc/php/conf.d/uploads.ini

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

RUN git clone https://github.com/edenhill/librdkafka.git \
    && cd librdkafka \
    && ./configure \
    && make \
    && make install \
    && pecl install rdkafka \
    && docker-php-ext-enable rdkafka

COPY . .
RUN composer install --optimize-autoloader
RUN composer dump-autoload --optimize

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt -y install nodejs
# RUN npm i -g pm2
RUN docker-php-ext-install intl opcache \
    && pecl install redis imagick \
    && docker-php-ext-enable opcache redis imagick \
    && cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
RUN apt-get clean \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN php artisan package:discover

RUN npm i && npm install -g dotenv && npm i -g pm2
RUN echo 'memory_limit = -1' >> /usr/local/etc/php/conf.d/docker-php-ram-limit.ini \
    && echo -e 'opcache.enable=1\nopcache.revalidate_freq=0\nopcache.validate_timestamps=0\nopcache.max_accelerated_files=10000\nopcache.max_wasted_percentage=10\nopcache.interned_strings_buffer=16\nopcache.fast_shutdown=1\nopcache.enable_cli=1\nopcache.jit_buffer_size=50M\nopcache.jit=tracing' >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini \
    && touch /usr/local/etc/php/conf.d/uploads.ini \
    && echo "upload_max_filesize = 80M;" >> /usr/local/etc/php/conf.d/uploads.ini

CMD tail -f /dev/null
