import { MigrationInterface, QueryRunner, Table, TableIndex } from "typeorm";

export class marginHistories1637840486910 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: "margin_histories",
        columns: [
          {
            name: "id",
            type: "bigint",
            isPrimary: true,
            isGenerated: true,
            generationStrategy: "increment",
            unsigned: true,
          },
          {
            name: "accountId",
            type: "bigint",
          },
          {
            name: "action",
            type: "varchar(20)",
          },
          {
            name: "orderId",
            type: "bigint",
            isNullable: true,
          },
          {
            name: "tradeId",
            type: "bigint",
            isNullable: true,
          },
          {
            name: "positionId",
            type: "bigint",
            isNullable: true,
          },
          {
            name: "leverage",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "leverageAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "positionUnrealisedPnl",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "positionUnrealisedPnlAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "riskLimit",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "riskLimitAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "riskValue",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "riskValueAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "entryPrice",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "entryPriceAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "entryValue",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "entryValueAfter",
            type: "decimal",
            precision: 30,
            scale: 10,
            default: null,
            isNullable: true,
          },
          {
            name: "currentQty",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "currentQtyAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "initMargin",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "initMarginAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "maintainMargin",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "maintainMarginAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "extraMargin",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "extraMarginAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "liquidationPrice",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "liquidationPriceAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "liquidationProgress",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "liquidationProgressAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "liquidationOrderId",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "liquidationOrderIdAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "pnlRanking",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "pnlRankingAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "realisedPnl",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "realisedPnlAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "latestRealisedPnl",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "latestRealisedPnlAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderBuyQty",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderBuyQtyAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderSellQty",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderSellQtyAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderBuyValue",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderBuyValueAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderSellValue",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderSellValueAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "balance",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "balanceAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "crossBalance",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "crossBalanceAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "crossMargin",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "crossMarginAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "isolatedBalance",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "isolatedBalanceAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "orderMargin",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "orderMarginAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderValue",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderValueAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderMargin",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "openOrderMarginAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "availableBalance",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "availableBalanceAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "maxAvailableBalance",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "maxAvailableBalanceAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "accountUnrealisedPnl",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "accountUnrealisedPnlAfter",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "orderValue",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "contractMargin",
            type: "decimal",
            precision: 22,
            scale: 8,
            default: null,
            isNullable: true,
          },
          {
            name: "operationId",
            type: "bigint",
            unsigned: true,
            default: null,
          },
          {
            name: "createdAt",
            type: "datetime",
            default: "CURRENT_TIMESTAMP",
          },
          {
            name: "updatedAt",
            type: "datetime",
            default: "CURRENT_TIMESTAMP",
          },
        ],
      }),
      true
    );

    await queryRunner.createIndices("margin_histories", [
      new TableIndex({
        columnNames: ["accountId"],
        isUnique: false,
        name: "IDX-margin_histories-accountId",
      }),
      new TableIndex({
        columnNames: ["orderId"],
        isUnique: false,
        name: "IDX-margin_histories-orderId",
      }),
      new TableIndex({
        columnNames: ["tradeId"],
        isUnique: false,
        name: "IDX-margin_histories-tradeId",
      }),
      new TableIndex({
        columnNames: ["positionId"],
        isUnique: false,
        name: "IDX-margin_histories-positionId",
      }),
      new TableIndex({
        columnNames: ["operationId"],
        isUnique: false,
        name: "IDX-margin_histories-operationId",
      }),
      new TableIndex({
        columnNames: ["createdAt"],
        isUnique: false,
        name: "IDX-margin_histories-createdAt",
      }),
    ]);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable("margin_histories");
  }
}
