package com.sotatek.future.enums;

public enum MarginHistoryAction {
  ACTIVATE_ORDER,
  MATCHING_BUY,
  MATCHING_SELL,
  CANCEL_ORDER,
  CANCEL_ERROR,
  MATCHING_ERROR,
  DEPOSIT,
  WITHDRAW,
  CHECK_LIQUIDATION,
  FUNDING,
  LIQUIDATION,
  COLLECT_LIQ_CLEARANCE_FEE,
  COLLECT_EXTRA_ISOLATED_MARGIN,
  COLLECT_EXTRA_CROSS_MARGIN
}
