export const INDEX_PRICE_PREFIX = "instrument_index_price_";
export const ORACLE_PRICE_PREFIX = "instrument_oracle_price_";
export const TICK_SIZE_DEFAULT = 0.01;

export const NEXT_TIME_MARKET = "next_time_market_";

export const LAST_PRICE_PREFIX = "instrument_last_price_";
export const KEY_CACHE_HEALTHCHECK_INDEX_PRICE = "healthcheck_index_price";
export const INDEX_PRICE_EXPRIRE_TIME = 40 * 60;
export const LAST_PRICE_TTL = 60 * 60; // 1시간
/**
 * Weighted by markets to caculate the correct indices
 * Please notice that total the weight my not be 100, it could be less than 100 or more than 100
 */
export const MetaWeightGroup = {
  BTCUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  ETHUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  BNBUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  LTCUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  XRPUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  SOLUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  TRXUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  MATICUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  LINKUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  MANAUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  FILUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  ATOMUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  AAVEUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  DOGEUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  DOTUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  UNIUSDT: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },

  BTCUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  ETHUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  BNBUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  LTCUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  XRPUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  USDTUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  SOLUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  TRXUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  MATICUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  LINKUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  MANAUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  FILUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  ATOMUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  AAVEUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  DOGEUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  DOTUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
  UNIUSD: {
    binance: 2,
    huobi: 1,
    okx: 1,
  },
};

export const MetaCommon = {
  // Skip data that not been updated for 10min
  timeframe: 600,
  // For testing purpose
  // timeframe: 3600,
};

export const MetaCandle = {
  binance: {
    baseUrl: "https://api1.binance.com",
    pairs: [
      { symbol: "BTCUSDT", group: "BTCUSD" },
      { symbol: "ETHUSDT", group: "ETHUSD" },
      { symbol: "BCHUSDT", group: "BCHUSD" },
      { symbol: "LTCUSDT", group: "LTCUSD" },
      { symbol: "LINKUSDT", group: "LINKUSD" },
      { symbol: "ENJUSDT", group: "ENJUSD" },
      { symbol: "AVAXUSDT", group: "AVAXUSD" },
      { symbol: "MATICUSDT", group: "MATICUSD" },
      { symbol: "DOGEUSDT", group: "DOGEUSD" },
      { symbol: "SOLUSDT", group: "SOLUSD" },
      { symbol: "AAVEUSDT", group: "AAVEUSD" },
      { symbol: "ATOMUSDT", group: "ATOMUSD" },
      { symbol: "YFIUSDT", group: "YFIUSD" },
      { symbol: "UNIUSDT", group: "UNIUSD" },
      { symbol: "SUSHIUSDT", group: "SUSHIUSD" },
      { symbol: "ALGOUSDT", group: "ALGOUSD" },
      { symbol: "EOSUSDT", group: "EOSUSD" },
      { symbol: "ZECUSDT", group: "ZECUSD" },
      { symbol: "DOTUSDT", group: "DOTUSD" },
      { symbol: "MKRUSDT", group: "MKRUSD" },
      { symbol: "SNXUSDT", group: "SNXUSD" },
      { symbol: "XMRUSDT", group: "XMRUSD" },
      { symbol: "ZRXUSDT", group: "ZRXUSD" },
      { symbol: "ADAUSDT", group: "ADAUSD" },
      { symbol: "COMPUSDT", group: "COMPUSD" },
      { symbol: "SHIBUSDT", group: "SHIBUSDT" },
    ],
    interval: "1m",
    limit: 100,
  },
  coinbase: {
    baseUrl: "https://api.exchange.coinbase.com",
    pairs: [
      { symbol: "BTC-USD", group: "BTCUSD" },
      { symbol: "ETH-USD", group: "ETHUSD" },
    ],
    granularity: 60,
  },
};

export const MetaMarket = {
  binance: {
    baseUrl: "https://api1.binance.com",
    pairs: [
      { symbol: "BTCUSDT", group: "BTCUSDT" },
      { symbol: "ETHUSDT", group: "ETHUSDT" },
      { symbol: "BNBUSDT", group: "BNBUSDT" },
      { symbol: "LTCUSDT", group: "LTCUSDT" },
      { symbol: "XRPUSDT", group: "XRPUSDT" },
      { symbol: "SOLUSDT", group: "SOLUSDT" },
      { symbol: "TRXUSDT", group: "TRXUSDT" },
      { symbol: "MATICUSDT", group: "MATICUSDT" },
      { symbol: "LINKUSDT", group: "LINKUSDT" },
      { symbol: "MANAUSDT", group: "MANAUSDT" },
      { symbol: "FILUSDT", group: "FILUSDT" },
      { symbol: "ATOMUSDT", group: "ATOMUSDT" },
      { symbol: "AAVEUSDT", group: "AAVEUSDT" },
      { symbol: "DOGEUSDT", group: "DOGEUSDT" },
      { symbol: "DOTUSDT", group: "DOTUSDT" },
      { symbol: "UNIUSDT", group: "UNIUSDT" },
      { symbol: "SHIBUSDT", group: "SHIBUSDT" },
    ],
  },
  // bitfinex: {
  //   baseUrl: 'https://api.bitfinex.com',
  //   pairs: [
  //     { symbol: 'btcusd', group: 'BTCUSD' },
  //     { symbol: 'ethusd', group: 'ETHUSD' },
  //     { symbol: 'ltcusd', group: 'LTCUSD' },
  //     { symbol: 'xrpusd', group: 'XRPUSD' },
  //     { symbol: 'solusd', group: 'SOLUSD' },
  //     { symbol: 'trxusd', group: 'TRXUSD' },
  //     { symbol: 'link:usd', group: 'LINKUSD' },
  //     { symbol: 'filusd', group: 'FILUSD' },
  //     { symbol: 'aave:usd', group: 'AAVEUSD' },
  //     { symbol: 'doge:usd', group: 'DOGEUSD' },
  //     { symbol: 'dotusd', group: 'DOTUSD' },
  //     { symbol: 'uniusd', group: 'UNIUSD' },
  //   ],
  // },
  // bitmax: {
  //   baseUrl: 'https://bitmax.io',
  //   pairs: [
  //     { symbol: 'BTC/USDT', group: 'BTCUSDT' },
  //     { symbol: 'ETH/USDT', group: 'ETHUSDT' },
  //     { symbol: 'BNB/USDT', group: 'BNBUSDT' },
  //     { symbol: 'LTC/USDT', group: 'LTCUSDT' },
  //     { symbol: 'XRP/USDT', group: 'XRPUSDT' },
  //     { symbol: 'SOL/USDT', group: 'SOLUSDT' },
  //     { symbol: 'TRX/USDT', group: 'TRXUSDT' },
  //     { symbol: 'MATIC/USDT', group: 'MATICUSDT' },
  //     { symbol: 'LINK/USDT', group: 'LINKUSDT' },
  //     { symbol: 'MANA/USDT', group: 'MANAUSDT' },
  //     { symbol: 'FIL/USDT', group: 'FILUSDT' },
  //     { symbol: 'ATOM/USDT', group: 'ATOMUSDT' },
  //     { symbol: 'AAVE/USDT', group: 'AAVEUSDT' },
  //     { symbol: 'DOGE/USDT', group: 'DOGEUSDT' },
  //     { symbol: 'DOT/USDT', group: 'DOTUSDT' },
  //     { symbol: 'UNI/USDT', group: 'UNIUSDT' },
  //     { symbol: 'BTC/USD', group: 'BTCUSD' },
  //     { symbol: 'ETH/USD', group: 'ETHUSD' },
  //     { symbol: 'BNB/USD', group: 'BNBUSD' },
  //     { symbol: 'XRP/USDT', group: 'XRPUSD' },
  //     { symbol: 'USDT/USD', group: 'USDTUSD' },
  //     { symbol: 'SOL/USD', group: 'SOLUSD' },
  //     { symbol: 'TRX/USD', group: 'TRXUSD' },
  //     { symbol: 'MATIC/USD', group: 'MATICUSD' },
  //     { symbol: 'LINK/USD', group: 'LINKUSD' },
  //     { symbol: 'ATOM/USD', group: 'ATOMUSD' },
  //     { symbol: 'DOT/USD', group: 'DOTUSD' },
  //   ],
  // },
  // bitstamp: {
  //   baseUrl: 'https://www.bitstamp.net',
  //   pairs: [
  //     { symbol: 'btcusd', group: 'BTCUSD' },
  //     { symbol: 'ethusd', group: 'ETHUSD' },
  //     { symbol: 'ltcusd', group: 'LTCUSD' },
  //     { symbol: 'xrpusd', group: 'XRPUSD' },
  //     { symbol: 'usdtusd', group: 'USDTUSD' },
  //     { symbol: 'solusd', group: 'SOLUSD' },
  //     { symbol: 'maticusd', group: 'MATICUSD' },
  //     { symbol: 'linkusd', group: 'LINKUSD' },
  //     { symbol: 'manausd', group: 'MANAUSD' },
  //     { symbol: 'aaveusd', group: 'AAVEUSD' },
  //     { symbol: 'dogeusd', group: 'DOGEUSD' },
  //     { symbol: 'dotusd', group: 'DOTUSD' },
  //     { symbol: 'uniusd', group: 'UNIUSD' },
  //     { symbol: 'btcusdt', group: 'BTCUSDT' },
  //     { symbol: 'ethusdt', group: 'ETHUSDT' },
  //     { symbol: 'xrpusdt', group: 'XRPUSDT' },
  //   ],
  // },
  // bittrex: {
  //   baseUrl: 'https://api.bittrex.com',
  //   pairs: [
  //     { symbol: 'BTC-USD', group: 'BTCUSD' },
  //     { symbol: 'ETH-USD', group: 'ETHUSD' },
  //     { symbol: 'LTC-USD', group: 'LTCUSD' },
  //     { symbol: 'XRP-USD', group: 'XRPUSD' },
  //     { symbol: 'SOL-USD', group: 'SOLUSD' },
  //     { symbol: 'TRX-USD', group: 'TRXUSD' },
  //     { symbol: 'MATIC-USD', group: 'MATICUSD' },
  //     { symbol: 'LINK-USD', group: 'LINKUSD' },
  //     { symbol: 'MANA-USD', group: 'MANAUSD' },
  //     { symbol: 'USDT-USD', group: 'USDTUSD' },
  //     { symbol: 'FIL-USD', group: 'FILUSD' },
  //     { symbol: 'ATOM-USD', group: 'ATOMUSD' },
  //     { symbol: 'AAVE-USD', group: 'AAVEUSD' },
  //     { symbol: 'DOGE-USD', group: 'DOGEUSD' },
  //     { symbol: 'DOT-USD', group: 'DOTUSD' },
  //     { symbol: 'UNI-USD', group: 'UNIUSD' },
  //     { symbol: 'BTC-USDT', group: 'BTCUSDT' },
  //     { symbol: 'ETH-USDT', group: 'ETHUSDT' },
  //     { symbol: 'LTC-USDT', group: 'LTCUSDT' },
  //     { symbol: 'XRP-USDT', group: 'XRPUSDT' },
  //     { symbol: 'SOL-USDT', group: 'SOLUSDT' },
  //     { symbol: 'TRX-USDT', group: 'TRXUSDT' },
  //     { symbol: 'MATIC-USDT', group: 'MATICUSDT' },
  //     { symbol: 'LINK-USDT', group: 'LINKUSDT' },
  //     { symbol: 'FIL-USDT', group: 'FILUSDT' },
  //     { symbol: 'ATOM-USDT', group: 'ATOMUSDT' },
  //     { symbol: 'AAVE-USDT', group: 'AAVEUSDT' },
  //     { symbol: 'DOGE-USDT', group: 'DOGEUSDT' },
  //     { symbol: 'DOT-USDT', group: 'DOTUSDT' },
  //     { symbol: 'UNI-USDT', group: 'UNIUSDT' },
  //   ],
  // },
  // coinbase: {
  //   baseUrl: 'https://api.exchange.coinbase.com',
  //   pairs: [
  //     { symbol: 'BTC-USD', group: 'BTCUSD' },
  //     { symbol: 'ETH-USD', group: 'ETHUSD' },
  //     { symbol: 'LTC-USD', group: 'LTCUSD' },
  //     { symbol: 'SOL-USD', group: 'SOLUSD' },
  //     { symbol: 'MATIC-USD', group: 'MATICUSD' },
  //     { symbol: 'LINK-USD', group: 'LINKUSD' },
  //     { symbol: 'MANA-USD', group: 'MANAUSD' },
  //     { symbol: 'USDT-USD', group: 'USDTUSD' },
  //     { symbol: 'FIL-USD', group: 'FILUSD' },
  //     { symbol: 'ATOM-USD', group: 'ATOMUSD' },
  //     { symbol: 'AAVE-USD', group: 'AAVEUSD' },
  //     { symbol: 'DOGE-USD', group: 'DOGEUSD' },
  //     { symbol: 'DOT-USD', group: 'DOTUSD' },
  //     { symbol: 'UNI-USD', group: 'UNIUSD' },
  //     { symbol: 'BTC-USDT', group: 'BTCUSDT' },
  //     { symbol: 'ETH-USDT', group: 'ETHUSDT' },
  //     { symbol: 'SOL-USDT', group: 'SOLUSDT' },
  //     { symbol: 'MATIC-USDT', group: 'MATICUSDT' },
  //     { symbol: 'LINK-USDT', group: 'LINKUSDT' },
  //     { symbol: 'ATOM-USDT', group: 'ATOMUSDT' },
  //     { symbol: 'DOGE-USDT', group: 'DOGEUSDT' },
  //     { symbol: 'DOT-USDT', group: 'DOTUSDT' },
  //   ],
  //   granularity: 60,
  // },
  // gateio: {
  //   baseUrl: 'https://data.gateapi.io',
  //   pairs: [
  //     { symbol: 'btc_usdt', group: 'BTCUSDT' },
  //     { symbol: 'eth_usdt', group: 'ETHUSDT' },
  //     { symbol: 'bnb_usdt', group: 'BNBUSDT' },
  //     { symbol: 'ltc_usdt', group: 'LTCUSDT' },
  //     { symbol: 'xrp_usdt', group: 'XRPUSDT' },
  //     { symbol: 'sol_usdt', group: 'SOLUSDT' },
  //     { symbol: 'trx_usdt', group: 'TRXUSDT' },
  //     { symbol: 'matic_usdt', group: 'MATICUSDT' },
  //     { symbol: 'link_usdt', group: 'LINKUSDT' },
  //     { symbol: 'mana_usdt', group: 'MANAUSDT' },
  //     { symbol: 'fil_usdt', group: 'FILUSDT' },
  //     { symbol: 'atom_usdt', group: 'ATOMUSDT' },
  //     { symbol: 'aave_usdt', group: 'AAVEUSDT' },
  //     { symbol: 'doge_usdt', group: 'DOGEUSDT' },
  //     { symbol: 'dot_usdt', group: 'DOTUSDT' },
  //     { symbol: 'uni_usdt', group: 'UNIUSDT' },
  //     { symbol: 'btc_usd', group: 'BTCUSD' },
  //     { symbol: 'eth_usd', group: 'ETHUSD' },
  //     { symbol: 'bnb_usd', group: 'BNBUSD' },
  //     { symbol: 'ltc_usd', group: 'LTCUSD' },
  //     { symbol: 'xrp_usd', group: 'XRPUSD' },
  //     { symbol: 'sol_usd', group: 'SOLUSD' },
  //     { symbol: 'trx_usd', group: 'TRXUSD' },
  //     { symbol: 'matic_usd', group: 'MATICUSD' },
  //     { symbol: 'link_usd', group: 'LINKUSD' },
  //     { symbol: 'usdt_usd', group: 'USDTUSD' },
  //     { symbol: 'aave_usd', group: 'AAVEUSD' },
  //     { symbol: 'doge_usd', group: 'DOGEUSD' },
  //     { symbol: 'uni_usd', group: 'UNIUSD' },
  //   ],
  // },
  // gemini: {
  //   baseUrl: 'https://api.gemini.com',
  //   pairs: [
  //     { symbol: 'btcusd', group: 'BTCUSD' },
  //     { symbol: 'ethusd', group: 'ETHUSD' },
  //     { symbol: 'ltcusd', group: 'LTCUSD' },
  //     { symbol: 'solusd', group: 'SOLUSD' },
  //     { symbol: 'maticusd', group: 'MATICUSD' },
  //     { symbol: 'linkusd', group: 'LINKUSD' },
  //     { symbol: 'manausd', group: 'MANAUSD' },
  //     { symbol: 'filusd', group: 'FILUSD' },
  //     { symbol: 'aaveusd', group: 'AAVEUSD' },
  //     { symbol: 'dogeusd', group: 'DOGEUSD' },
  //     { symbol: 'dotusd', group: 'DOTUSD' },
  //     { symbol: 'uniusd', group: 'UNIUSD' },
  //   ],
  // },
  // hitbtc: {
  //   baseUrl: 'https://api.hitbtc.com',
  //   pairs: [
  //     { symbol: 'BTCUSDT', group: 'BTCUSDT' },
  //     { symbol: 'ETHUSDT', group: 'ETHUSDT' },
  //     { symbol: 'BNBUSDT', group: 'BNBUSDT' },
  //     { symbol: 'LTCUSDT', group: 'LTCUSDT' },
  //     { symbol: 'XRPUSDT', group: 'XRPUSDT' },
  //     { symbol: 'SOLUSDT', group: 'SOLUSDT' },
  //     { symbol: 'TRXUSDT', group: 'TRXUSDT' },
  //     { symbol: 'MATICUSDT', group: 'MATICUSDT' },
  //     { symbol: 'LINKUSDT', group: 'LINKUSDT' },
  //     { symbol: 'MANAUSDT', group: 'MANAUSDT' },
  //     { symbol: 'FILUSDT', group: 'FILUSDT' },
  //     { symbol: 'ATOMUSDT', group: 'ATOMUSDT' },
  //     { symbol: 'AAVEUSDT', group: 'AAVEUSDT' },
  //     { symbol: 'DOGEUSDT', group: 'DOGEUSDT' },
  //     { symbol: 'DOTUSDT', group: 'DOTUSDT' },
  //     { symbol: 'UNIUSDT', group: 'UNIUSDT' },
  //   ],
  // },
  huobi: {
    baseUrl: "https://api.huobi.pro",
    pairs: [
      { symbol: "btcusdt", group: "BTCUSDT" },
      { symbol: "ethusdt", group: "ETHUSDT" },
      { symbol: "bnbusdt", group: "BNBUSDT" },
      { symbol: "ltcusdt", group: "LTCUSDT" },
      { symbol: "xrpusdt", group: "XRPUSDT" },
      { symbol: "solusdt", group: "SOLUSDT" },
      { symbol: "trxusdt", group: "TRXUSDT" },
      { symbol: "maticusdt", group: "MATICUSDT" },
      { symbol: "linkusdt", group: "LINKUSDT" },
      { symbol: "manausdt", group: "MANAUSDT" },
      { symbol: "filusdt", group: "FILUSDT" },
      { symbol: "atomusdt", group: "ATOMUSDT" },
      { symbol: "aaveusdt", group: "AAVEUSDT" },
      { symbol: "dogeusdt", group: "DOGEUSDT" },
      { symbol: "dotusdt", group: "DOTUSDT" },
      { symbol: "uniusdt", group: "UNIUSDT" },
      { symbol: "shibusdt", group: "SHIBUSDT" },
    ],
  },
  // kraken: {
  //   baseUrl: 'https://api.kraken.com',
  //   pairs: [
  //     { symbol: 'BTCUSDT', group: 'BTCUSDT' },
  //     { symbol: 'ETHUSDT', group: 'ETHUSDT' },
  //     { symbol: 'LTCUSDT', group: 'LTCUSDT' },
  //     { symbol: 'XRPUSDT', group: 'XRPUSDT' },
  //     { symbol: 'SOLUSDT', group: 'SOLUSDT' },
  //     { symbol: 'MATICUSDT', group: 'MATICUSDT' },
  //     { symbol: 'LINKUSDT', group: 'LINKUSDT' },
  //     { symbol: 'MANAUSDT', group: 'MANAUSDT' },
  //     { symbol: 'ATOMUSDT', group: 'ATOMUSDT' },
  //     { symbol: 'DOGEUSDT', group: 'DOGEUSDT' },
  //     { symbol: 'DOTUSDT', group: 'DOTUSDT' },
  //     { symbol: 'BTCUSD', group: 'BTCUSD' },
  //     { symbol: 'ETHUSD', group: 'ETHUSD' },
  //     { symbol: 'LTCUSD', group: 'LTCUSD' },
  //     { symbol: 'XRPUSD', group: 'XRPUSD' },
  //     { symbol: 'SOLUSD', group: 'SOLUSD' },
  //     { symbol: 'USDTUSD', group: 'USDTUSD' },
  //     { symbol: 'TRXUSD', group: 'TRXUSD' },
  //     { symbol: 'MATICUSD', group: 'MATICUSD' },
  //     { symbol: 'LINKUSD', group: 'LINKUSD' },
  //     { symbol: 'MANAUSD', group: 'MANAUSD' },
  //     { symbol: 'FILUSD', group: 'FILUSD' },
  //     { symbol: 'ATOMUSD', group: 'ATOMUSD' },
  //     { symbol: 'AAVEUSD', group: 'AAVEUSD' },
  //     { symbol: 'DOGEUSD', group: 'DOGEUSD' },
  //     { symbol: 'DOTUSD', group: 'DOTUSD' },
  //     { symbol: 'UNIUSD', group: 'UNIUSD' },
  //   ],
  // },
  // mxc: {
  //   baseUrl: 'https://contract.mexc.com',
  //   pairs: [
  //     { symbol: 'BTC_USDT', group: 'BTCUSDT' },
  //     { symbol: 'ETH_USDT', group: 'ETHUSDT' },
  //     { symbol: 'BNB_USDT', group: 'BNBUSDT' },
  //     { symbol: 'LTC_USDT', group: 'LTCUSDT' },
  //     { symbol: 'XRP_USDT', group: 'XRPUSDT' },
  //     { symbol: 'SOL_USDT', group: 'SOLUSDT' },
  //     { symbol: 'TRX_USDT', group: 'TRXUSDT' },
  //     { symbol: 'MATIC_USDT', group: 'MATICUSDT' },
  //     { symbol: 'LINK_USDT', group: 'LINKUSDT' },
  //     { symbol: 'MANA_USDT', group: 'MANAUSDT' },
  //     { symbol: 'ATOM_USDT', group: 'ATOMUSDT' },
  //     { symbol: 'AAVE_USDT', group: 'AAVEUSDT' },
  //     { symbol: 'DOGE_USDT', group: 'DOGEUSDT' },
  //     { symbol: 'DOT_USDT', group: 'DOTUSDT' },
  //     { symbol: 'UNI_USDT', group: 'UNIUSDT' },
  //     { symbol: 'BTC_USD', group: 'BTCUSD' },
  //     { symbol: 'ETH_USD', group: 'ETHUSD' },
  //     { symbol: 'XRP_USD', group: 'XRPUSD' },
  //     { symbol: 'ATOM_USD', group: 'ATOMUSD' },
  //   ],
  // },
  okx: {
    baseUrl: "https://www.okx.com",
    pairs: [
      { symbol: "BTC-USDT", group: "BTCUSDT" },
      { symbol: "ETH-USDT", group: "ETHUSDT" },
      { symbol: "BNB-USDT", group: "BNBUSDT" },
      { symbol: "LTC-USDT", group: "LTCUSDT" },
      { symbol: "XRP-USDT", group: "XRPUSDT" },
      { symbol: "SOL-USDT", group: "SOLUSDT" },
      { symbol: "TRX-USDT", group: "TRXUSDT" },
      { symbol: "MATIC-USDT", group: "MATICUSDT" },
      { symbol: "LINK-USDT", group: "LINKUSDT" },
      { symbol: "MANA-USDT", group: "MANAUSDT" },
      { symbol: "FIL-USDT", group: "FILUSDT" },
      { symbol: "ATOM-USDT", group: "ATOMUSDT" },
      { symbol: "AAVE-USDT", group: "AAVEUSDT" },
      { symbol: "DOGE-USDT", group: "DOGEUSDT" },
      { symbol: "DOT-USDT", group: "DOTUSDT" },
      { symbol: "UNI-USDT", group: "UNIUSDT" },
      { symbol: "SHIB-USDT", group: "SHIBUSDT" },
    ],
  },
};

// USD price deviates from USDT price (percent)
export const deviatePercentUSDTUSD = [0.1, 0.5];
